# Generated by Django 5.2 on 2025-04-13 14:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Under Maintenance'), ('error', 'Error'), ('disabled', 'Disabled')], default='offline', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('port', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WashProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_per_minute', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_minute', models.DecimalField(decimal_places=2, help_text='Base price per minute', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('default_timeout', models.PositiveIntegerField(default=300, help_text='Default timeout in seconds')),
                ('bonus_duration_enabled', models.BooleanField(default=False)),
                ('bonus_duration_amount', models.PositiveIntegerField(default=0, help_text='Additional bonus time in seconds')),
                ('valve_reset_timeout', models.PositiveIntegerField(default=60, help_text='Valve reset timeout in seconds')),
                ('is_template', models.BooleanField(default=False)),
                ('template_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('command', 'Command'), ('status_change', 'Status Change')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('error', 'Error'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('total_duration', models.PositiveIntegerField(default=0, help_text='Total duration in seconds')),
                ('client_card', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_charged', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('bonus_time_used', models.PositiveIntegerField(default=0, help_text='Bonus time used in seconds')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='devices.device')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='devices.washprogram')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceProgramSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_enabled', models.BooleanField(default=True)),
                ('device_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.deviceconfiguration')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.washprogram')),
            ],
            options={
                'unique_together': {('device_config', 'program')},
            },
        ),
        migrations.AddField(
            model_name='deviceconfiguration',
            name='custom_programs',
            field=models.ManyToManyField(through='devices.DeviceProgramSetting', to='devices.washprogram'),
        ),
    ]
