# Generated by Django 5.2 on 2025-04-23 12:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_deviceconfiguration_engine_performance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='washprogram',
            name='price_per_second',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.16667'), max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
