# Generated by Django 5.2 on 2025-04-23 12:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_washprogram_price_per_second'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washprogram',
            name='price_per_minute',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='washprogram',
            name='price_per_second',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.16667'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
