# Generated by Django 5.2 on 2025-04-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_washprogram_price_per_minute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_handshake_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='registration_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='device',
            name='registration_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
