# Generated by Django 5.2 on 2025-04-16 15:04

import reporting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportjob',
            old_name='generated_file',
            new_name='chart_file',
        ),
        migrations.AddField(
            model_name='reportjob',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to=reporting.models.report_file_path),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=reporting.models.report_file_path),
        ),
    ]
